// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/content-scripts/content.js"
    | "/icons/icon_128x128.png"
    | "/icons/icon_128x128_2.png"
    | "/icons/icon_16x16.png"
    | "/icons/icon_48x48.png"
    | "/icons/icon_64x64.png"
    | "/icons/stop_48x48.png"
    | "/icons/voxlocal-mic.png"
    | "/icons/voxlocal-stop.png"
    | "/screenshots/screenshot_1.png"
    | "/screenshots/screenshot_2.png"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
